### ISSUE TITLE
wont work with directories

### ISSUE THREAD

**Issue by croo** [detly/arkfind#8]
Hi!

The script wont work with directories under centOS, python 2.7.5.

with file as parameter:
[root@localhost war]# python ~/arkfind -g ../war/theme.war "*.ftl"
../war/theme.war
  > templates/header.ftl

with the same directory as parameter:
[root@localhost war]# python ~/arkfind -g ../war/ "*.ftl"
Traceback (most recent call last):
  File "/root/arkfind", line 618, in <module>
    json=args.json
  File "/root/arkfind", line 572, in main
    archive_search(Path.os(base_path), search_func, reporter)
  File "/root/arkfind", line 529, in archive_search
    base_path_kind = magic.from_file(base_path.joined.encode(sys.getfilesystemencoding()), mime=True)
  File "/usr/lib/python2.7/site-packages/magic.py", line 131, in from_file
    return m.from_file(filename)
  File "/usr/lib/python2.7/site-packages/magic.py", line 81, in from_file
    with open(filename):
IOError: [Errno 21] Is a directory: '../war'

**Comment by croo** [comment]
I was able to make it work by changing python-magic version 0.4.13 to 0.4.3.

**Comment by detly** [comment]
Relevant: https://github.com/ahupp/python-magic/issues/170
